run:
  timeout: 5m

skip-dirs:
  - dissertations
  - ./dissertations
  - dissertations/*

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - errcheck

linters-settings:
  errcheck:
    exclude-functions:
      - github.com/gin-gonic/gin.Context.AbortWithError

issues:
  exclude-use-default: false
