services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./dissertations:/usr/src/app/dissertations
    environment:
      MAIL_PASSWORD: "vVtVASLsViAdwF6"
    container_name: "kasper-back"

  front:
    image: "jackblack178/kasper-front:localhost"
    ports:
      - "8082:80"  # Replaced port 80 with 8082
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server
    container_name: "kasper-front"

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: uir_draft
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./new_kasper.sql:/var/desctop.sql

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
    name: kasper-test

volumes:
  pgdata: {}
