version: "3.7"
services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./dissertations:/usr/src/app/dissertations
    extra_hosts:
      - "host.docker.internal:host-gateway"