version: '3' 
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    restart: always
    volumes:
      - ./dissertations:/usr/src/app/dissertations
    environment:
      MAIL_PASSWORD: "vVtVASLsViAdwF6"
    container_name: "kasper-back"

  front:
    image: pavelsem21/kasper-front:0.1.9.6.2
    environment:
    # VITE_API_URL: "http://localhost:8080/api"
    #  VITE_API_URL: "http://server:8080/api"
    #   VITE_API_URL: "https://mephi-22.ru/api"
        VITE_API_URL: "https://kaspermephi.ru/api"
    ports:
      - "8082:5173"
    restart: always
    depends_on:
      - server
    container_name: "kasper-front"

  postgres:
    image: postgres:16
    container_name: postgres_new
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pOsTgReSpAsS-!234*
      POSTGRES_DB: uir_draft
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./new_kasper.sql:/var/desctop.sql
      
      

networks:
  default:
    driver: bridge
    name: kasper-test
volumes:
  pgdata: {}

