version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./dissertations:/usr/src/app/dissertations
    extra_hosts:
      - "database:127.0.0.1"