version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./dissertations:/usr/src/app/dissertations
    extra_hosts:
      - "host.docker.internal:host-gateway"