version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    restart: always
    volumes:
      - ./dissertations:/usr/src/app/dissertations
    environment:
      MAIL_PASSWORD: "devPassword"
    container_name: "kasper-back-dev"
    extra_hosts:
      - "database:your-dev-db-ip"

  front:
    image: "jackblack178/kasper-front:dev"
    ports:
      - "8081:5173"
    restart: always
    depends_on:
      - server
    container_name: "kasper-front-dev"
