version: '3' 
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./dissertations:/usr/src/app/dissertations
    environment:
      MAIL_PASSWORD: "vVtVASLsViAdwF6"
    container_name: "kasper-back"

  front:
    image: pavelsem21/kasper-front:0.1.4
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - server
    container_name: "kasper-front"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: uir_draft
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./new_kasper.sql:/var/desctop.sql

networks:
  default:
    driver: bridge
    name: kasper-test

volumes:
  pgdata: {}


