name: Deploy to Production Server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key and SSH command
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SERVER_PORT_prod }} ${{ secrets.SERVER_HOST_prod }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy Docker files to Server
      run: |
        scp -P ${{ secrets.SERVER_PORT_prod }} docker-compose-prod.yaml Dockerfile ${{ secrets.SERVER_USER_prod }}@${{ secrets.SERVER_HOST_prod }}:/root/kasper-server

    - name: Deploy to Server using Docker
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT_prod }} ${{ secrets.SERVER_USER_prod }}@${{ secrets.SERVER_HOST_prod }} <<EOF
        cd /path/to/your/project
        echo ${{ secrets.SERVER_PASSWORD_prod }} | sudo -S docker-compose -f docker-compose-prod.yaml down
        echo ${{ secrets.SERVER_PASSWORD_prod }} | sudo -S docker-compose -f docker-compose-prod.yaml up --build -d
        EOF
