name: Deploy to Production Server
on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key and SSH agent
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.RELEASE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.RELEASE_SERVER_PORT }} ${{ secrets.RELEASE_SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.RELEASE_SERVER_PORT }} root@${{ secrets.RELEASE_SERVER_HOST }} "echo SSH connection successful"

    - name: Copy repository to server
      run: |
        rsync -avz --progress -e "ssh -p ${{ secrets.RELEASE_SERVER_PORT }} -o StrictHostKeyChecking=no" --exclude '.git' ./ root@${{ secrets.RELEASE_SERVER_HOST }}:/var/www/www-root/data/www/mephi-22.ru/

    - name: Docker Compose Down
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.RELEASE_SERVER_PORT }} root@${{ secrets.RELEASE_SERVER_HOST }} \
        "docker-compose -f /var/www/www-root/data/www/mephi-22.ru/docker-compose-prod.yaml down"

    - name: Docker Compose Up and Rebuild
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.RELEASE_SERVER_PORT }} root@${{ secrets.RELEASE_SERVER_HOST }} \
        "docker-compose -f /var/www/www-root/data/www/mephi-22.ru/docker-compose-prod.yaml up --build -d"
