name: Deploy to Production Server
on:
  push:
    branches:
      - master
      - pptx-gen-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key and SSH command
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SERVER_PORT_prod }} ${{ secrets.SERVER_HOST_prod }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Проверка прав на SSH ключ
        ls -la ~/.ssh/
        cat ~/.ssh/id_rsa

    - name: Copy entire repository to Server
      run: |
        rsync -avz --progress -e "ssh -p ${{ secrets.SERVER_PORT_prod }} -o StrictHostKeyChecking=no" --exclude '.git' ./ ${{ secrets.SERVER_USER_prod }}@${{ secrets.SERVER_HOST_prod }}:/root/kasper-server
        # Проверка состояния после rsync
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT_prod }} ${{ secrets.SERVER_USER_prod }}@${{ secrets.SERVER_HOST_prod }} "ls -R /root/kasper-server"

    - name: Docker Compose Down
      run: |
        ssh -t -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=480 -p ${{ secrets.SERVER_PORT_prod }} ${{ secrets.SERVER_USER_prod }}@${{ secrets.SERVER_HOST_prod }} "echo ${{ secrets.SERVER_PASSWORD_prod }} | sudo -S docker-compose -f /root/kasper-server/docker-compose-prod.yaml down"

    - name: Docker Compose Up and Rebuild
      run: |
        ssh -t -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=480 -p ${{ secrets.SERVER_PORT_prod }} ${{ secrets.SERVER_USER_prod }}@${{ secrets.SERVER_HOST_prod }} "echo ${{ secrets.SERVER_PASSWORD_prod }} | sudo -S docker-compose -f /root/kasper-server/docker-compose-prod.yaml up --build -d"
